sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-075.pdf --upload --lsstdoc DMTN-075.tex --env=travis --ltd-product dmtn-075"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "wMt0y8ALbEXELl6OhPSTf+4RLwb6j/ODWCupUIPv310QVDOUQgjJ8Ym8RZMvx18VwVLkw0jROlYC/bTnIoE1WJT1SLW9q68UDaKn1+3lUdyLZpUcm/4n5tlGeSrhxWK0Crvl06sfrIW6oeD92B9fdKZtjZ0pekfyXuBNoqUYfY6fgh+MtyQOuZd3R8W6uk3NNGhZDv0osBC6IED5lGQPRTmUVfTSnbBcbRupiMwjfEW7bh0lI8wKAzzOHU3eLk+54KGjSCU0vRSRF22cbiWMS3fHHsbezFqGiSnzbv72gOI7fZGfXvpqEFzuGXbfOJI3sMdJPKOfvUKBqSYXYZe0LXPqJNtllfaeJ2DqVaPEGedRusQIR4UGSUbqjIH4bDEsz8lJP+ztOIustwSd4o1bAoTM1X1Kmp6b7lE631BeusI+69y39XYYGYBQGvOw8OfwU1sVzvXOH9G6/TLx8rT86O3DBo1+jDgEyTUBkW+nwaBPu3dv/1mnjNdBlBXB6ufTPJvORTS9Yh0nE60LvEB0/WSakPSoFaPWr1ajXYoX1BNUI6ovvuXxPCmPEH279hVrcgL49hYws7MiVyJpnZ94w2CGnmyULIoEsxl94FlL9GRCJ4KR23syTEMvRtWbqkdG6dxv6KLPQ2f7xe3cn0JZnL0eAr1OhqT5iWLCj0XcxsQ="
    - secure: "v+5QJQs3KTuHzNI7GQUDnY/P43yQpNgK0FvR+PyveqVAAdxtrXTM7ewaN2UtuZpLNXNemavZgPYqDjAG2Nd9zt7uWfNjGkAj14uOM4QLY1x8E6Wrs8a74LPNkxLqy+Z8rgboCE/8gLvbV/hiikqz3DA39AkYlReo65RWZyJGI/deTo3v0o5yja6Cf8x1K5cAIDvXLjUe13ZIk5bBr2GyesQLZKef9qrl1agIqCjMCccM3WUoT72DcVPBppqf55xKaGRDW4ivdkhmLPmrmY7ji/o7zJ3K2eA0oAH4NjAkCJnyWon9xOrlqXa0CpRiXZ7ZFC4O1tvb9x7h9YcNP05376f/BtJ0pf1Ujb/ZjN2YVHoZT1SJZ8phrmyR873XbqLhaesB6rFy+8RfHq1UtXjcRnpuOmQMG3xn9KuL1R2JgfiKqeVLZEUTBZTY731pRkxS1di/3SCJCEPma272SNeOvbKx5isufv6OV4HNeyJ+CPfcybYvBp1h42bSJqiuEcjxrpBPjRB3Q1dJ1D55q/pJHOshmuehW2elTJHaS0XY7TgvFuRJnhwdnJCYJSP8gw2OL2oEYkwALxjZqfxGwuPeQZ5yY0jOv7h8RQaHPa2cyX+POILQGb6WtjrRhsdNyacKV+qZc6GeOVQgXEVkTni4INkJokNdslG4yFj/qlv9N7I="
